config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { cas_sessions: "simple_cas" }
  root to: "collections#index"

  get "help", to: "help#help"

  get "404", to: "errors#catch_404"
  get "500", to: "errors#catch_500"

  resource :masquerades, only: [:new, :create] do
    get :cancel
  end

  resources :errors

  resources :collections,
            only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :import_google_sheet_callback, controller: "import"
      get :export_google_sheet_callback, controller: "export"
    end

    member do
      site_setup_constraints = { form: /homepage|collection_introduction|about_text|copyright_text|site_path/ }
      get :site_setup
      get "site_setup/:form", to: "collections#site_setup", as: :site_setup_form, constraints: site_setup_constraints
      put "site_setup/:form", to: "collections#site_setup_update", as: :site_setup_update_form, constraints: site_setup_constraints
      settings_constraints = { form: /general|metadata/ }
      get :settings
      get "settings/:form", to: "collections#settings", as: :settings_form, constraints: settings_constraints
      put "settings/:form", to: "collections#settings_update", as: :settings_update_form, constraints: settings_constraints
      put :publish
      put :unpublish
      post :get_google_import_authorization_uri, controller: "import"
      post :get_google_export_authorization_uri, controller: "export"
    end

    resources :items, only: [:index, :new, :create]
    resources :showcases, only: [:index, :new, :create]
    resources :pages, only: [:index, :new, :create]

    resources :editors, only: [:index, :create, :destroy] do
      collection do
        get :user_search
      end
    end
  end

  resources :items, only: [:edit, :update, :destroy] do
    member do
      put :publish
      put :unpublish
    end
    resources :children, controller: "item_children", only: [:new, :create]
  end

  resources :showcases, only: [:show, :edit, :update, :destroy] do
    member do
      get :title
      put :publish
      put :unpublish
    end
    resources :sections, only: [:index, :new, :create]
  end

  resources :pages, only: [:edit, :update, :destroy]

  resources :sections, only: [:edit, :update, :destroy]

  namespace :v1 do
    resources :collections,
              only: [:show, :index],
              defaults: { format: :json } do
      put :publish, defaults: { format: :json }
      put :unpublish, defaults: { format: :json }
      put :preview_mode, defaults: { format: :json }
      get :metadata_configuration, defaults: { format: :json }
      get :site_path, defaults: { format: :json }
      put :site_path, to: "collections#site_path_update", defaults: { format: :json }
      resources :search, only: [:index], defaults: { format: :json }
      resources :items, only: [:index, :create], defaults: { format: :json }
      resources :showcases, only: [:index], defaults: { format: :json }
      resources :pages, only: [:index], defaults: { format: :json }
      resource :configurations, defaults: { format: :json }, only: [:show] do
        resources :metadata_fields, only: [:create, :update, :destroy], defaults: { format: :json }
      end
    end
    resources :items,
              only: [:show, :update],
              defaults: { format: :json } do
      get :showcases, defaults: { format: :json }
    end
    resources :showcases, only: [:show], defaults: { format: :json }
    resources :pages, only: [:show], defaults: { format: :json }
    resources :sections, only: [:show], defaults: { format: :json }
  end

  namespace :api do
    resources :collections,
              only: [:index, :show],
              constraints: { format: /json/ } do
      resources :items, only: [:index, :show], constraints: { format: /json/ }
    end
  end

  namespace :admin do
    get "/", to: "administration#index"
    resources :external_collections
    resources :administrators, only: [:index, :create, :destroy] do
      collection do
        get :user_search
      end
    end
  end

  scope "/admin_old" do
    resources :users do
      put :set_admin
      put :revoke_admin
    end

    # NOTE About this route.
    # the "ids" that are searched on can have "." in the
    # and that throws off the rails routing. They need to
    # be passed in as query params and not as part of the
    # get string that is not /discovery_test_id/i,adf.adsfwe.adsfsdf
    # but as /discovery_test_id?id=i,adf.adsfwe.adsfsdf
    get "discovery_id_test", to: "discovery_id_test#show"
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :items
  has_many :collection_users
  has_many :users, through: :collection_users
  has_many :showcases
  has_many :pages
  has_one :honeypot_image
  has_one :collection_configuration

  has_attached_file :image,
                    restricted_characters: /[&$+,\/:;=?@<>\[\]{}\|\\^~%#]/
  has_attached_file :uploaded_image,
                    restricted_characters: /[&$+,\/:;=?@<>\[\]{}\|\\^~%#]/
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :uploaded_image, content_type: /\Aimage\/.*\Z/
  validates :name_line_1, :unique_id, presence: true

  has_paper_trail

  def name
    if name_line_2.present?
      "#{name_line_1} #{name_line_2}"
    else
      name_line_1
    end
  end

  def items_json_url
    "/api/collections/#{id}/items.json?include=image"
  end

  def item_json_url(item_id)
    "/api/collections/#{id}/items/#{item_id}.json?include=image"
  end
end

app/controllers/api/collections_controller.rb
module API
  class CollectionsController < APIController
    def index
      @collections = Collection.all
      respond_to do |format|
        format.json { render json: GenerateCollectionJSON.call(@collections) }
      end
    end

    def show
      @collection = Collection.find(params[:id])
      respond_to do |format|
        format.json { render json: GenerateCollectionJSON.call(@collection) }
      end
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = CollectionQuery.new.for_editor(current_user)
    cache_key = CacheKeys::Generator.new(key_generator: CacheKeys::Custom::Collections,
                                         action: "index",
                                         collections: @collections)
    fresh_when(etag: cache_key.generate)
  end

  def show
    redirect_to collection_items_path(params[:id])
  end

  def new
    check_admin_or_admin_masquerading_permission!

    @collection = CollectionQuery.new.build
  end

  def create
    check_admin_or_admin_masquerading_permission!

    @collection = CollectionQuery.new.build

    if SaveCollection.call(@collection, save_params)
      flash[:notice] = t(".success")
      redirect_to collection_path(@collection)
    else
      render :new
    end
  end

  def settings
    @collection = CollectionQuery.new.find(params[:id])
    check_user_edits!(@collection)

    cache_key = CacheKeys::Generator.new(key_generator: CacheKeys::Custom::Collections,
                                         action: "settings",
                                         collection: @collection)
    fresh_when(etag: cache_key.generate)
  end

  def settings_update
    @collection = CollectionQuery.new.find(params[:id])
    check_user_edits!(@collection)

    if SaveCollection.call(@collection, save_params)
      flash[:notice] = t(".success")
      redirect_to settings_form_collection_path(@collection, form: params[:form])
    else
      render :settings
    end
  end

  def destroy
    check_admin_or_admin_masquerading_permission!

    @collection = CollectionQuery.new.find(params[:id])
    Destroy::Collection.new.cascade!(collection: @collection)

    flash[:notice] = t(".success")
    redirect_to collections_path
  end

  def site_setup
    @collection = CollectionQuery.new.find(params[:id])
    check_user_edits!(@collection)

    cache_key = CacheKeys::Generator.new(key_generator: CacheKeys::Custom::Collections,
                                         action: "site_setup",
                                         collection: @collection)
    fresh_when(etag: cache_key.generate)
  end

  def site_setup_update # rubocop:disable Metrics/AbcSize
    @collection = CollectionQuery.new.find(params[:id])
    check_user_edits!(@collection)

    if SaveCollection.call(@collection, save_params)
      flash[:notice] = t(".success")
      redirect_to site_setup_form_collection_path(@collection, form: params[:form])
    else
      render :site_setup
    end
  end

  def publish
    collection = CollectionQuery.new.find(params[:id])
    check_user_edits!(collection)

    if Publish.call(collection)
      flash[:notice] = t(".success")
      redirect_to edit_collection_path(collection)
    else
      render :edit
    end
  end

  def unpublish
    collection = CollectionQuery.new.find(params[:id])
    check_user_edits!(collection)

    if Unpublish.call(collection)
      flash[:notice] = t(".success")
      redirect_to edit_collection_path(collection)
    else
      render :edit
    end
  end

  protected

  def save_params
    params.require(:collection).permit(
      :name_line_1,
      :name_line_2,
      :description,
      :id,
      :enable_search,
      :enable_browse,
      :site_intro,
      :short_intro,
      :hide_title_on_home_page,
      :uploaded_image,
      :about,
      :copyright,
      :site_path)
  end
end

app/controllers/v1/collections_controller.rb
module V1
  class CollectionsController < APIController
    def index
      @collections = CollectionQuery.new.public_collections

      cache_key = CacheKeys::Generator.new(key_generator: CacheKeys::Custom::V1Collections,
                                           action: "index",
                                           collections: @collections)
      fresh_when(etag: cache_key.generate)
    end

    def show
      @collection = CollectionQuery.new.public_find(params[:id])

      cache_key = CacheKeys::Generator.new(key_generator: CacheKeys::Custom::V1Collections,
                                           action: "show",
                                           collection: @collection)
      fresh_when(etag: cache_key.generate)
    end

    def publish
      @collection = CollectionQuery.new.any_find(params[:collection_id])

      return if rendered_forbidden?(@collection)

      @return_value = Publish.call(@collection)

      respond_to do |format|
        format.json { render json: { status: @return_value }.to_json }
      end
    end

    def unpublish
      @collection = CollectionQuery.new.any_find(params[:collection_id])

      return if rendered_forbidden?(@collection)

      @return_value = Unpublish.call(@collection)

      respond_to do |format|
        format.json { render json: { status: @return_value }.to_json }
      end
    end

    def preview_mode
      @collection = CollectionQuery.new.any_find(params[:collection_id])

      return if rendered_forbidden?(@collection)

      @return_value = SetCollectionPreviewMode.call(@collection, params[:value])

      respond_to do |format|
        format.json { render json: { status: @return_value }.to_json }
      end
    end

    def metadata_configuration
      collection = CollectionQuery.new.any_find(params[:collection_id])
      @configuration = CollectionConfigurationQuery.new(collection).find
      @configuration = Metadata::Configuration.new(@configuration)
      @configuration = V1::MetadataConfigurationJSON.new(@configuration)

      respond_to do |format|
        format.json { render json: @configuration.to_json }
      end
    end

    def site_path
      collection = CollectionQuery.new.any_find(params[:collection_id])
      @collection = CollectionJSONDecorator.new(collection)
      @site_path = SiteObjectsQuery.new.all(collection: collection)
      cache_key = CacheKeys::Generator.new(key_generator: CacheKeys::Custom::V1Collections,
                                           action: "site_path",
                                           collection: collection, site_path: @site_path)
      fresh_when(etag: cache_key.generate)
    end

    def site_path_update
      @collection = CollectionQuery.new.any_find(params[:collection_id])

      return if rendered_forbidden?(@collection)

      site_path = SiteObjectsQuery.new.public_to_private_json(json_string: params[:site_path])
      @return_value = SaveCollection.call(@collection, site_path: site_path)

      respond_to do |format|
        format.json { render json: { status: @return_value }.to_json }
      end
    end
  end
end

app/views/collections/_about_text_form.html.erb
<%= f.input :about, input_html: { class: 'honeycomb_redactor'  } %>

<h3>Copy and Paste Example</h3>
<hr>

<h5>Name of Curator</h5>
<p><em>Title or Position</em><br/>Hesburgh Libraries</p>
<p>p: 124-123-1234<br/>e: name@nd.edu</p>

<hr>

app/views/collections/_collection_introduction_form.html.erb
<%= f.input :site_intro, input_html: { class: 'honeycomb_image_redactor'  } %>
<%= f.input :unique_id, as: :hidden, input_html: { id: "image_collection_unique_id", value: @collection.unique_id } %>

app/views/collections/_copyright_text_form.html.erb
<%= f.input :copyright, input_html: { class: "honeycomb_redactor" } %>
<h3>Copy and Paste Example</h3>
<hr>
<p><a href="http://www.nd.edu/copyright/">Copyright</a> <%= Date.today.year.to_s %> <a href="http://www.nd.edu">University of Notre Dame</a></p>

app/views/collections/_form.html.erb
<%= display_errors(@collection) %>

<%= f.input :name_line_1 %>
<%= f.input :name_line_2 %>
<%= render partial: 'search_and_browse_form', locals: { f: f } %>

app/views/collections/_general_settings_form.html.erb
<%= render :partial => 'general_settings_subform', locals: { f: f } %>

<%= f.button :submit, value: t('buttons.save'), :class => 'btn-primary' %>
<%= DeletePanel.new(@collection).display  %>

app/views/collections/_general_settings_subform.html.erb
<%= display_errors(@collection) %>

<%= f.input :name_line_1 %>
<%= f.input :name_line_2 %>
<%= render partial: 'search_and_browse_form', locals: { f: f } %>

app/views/collections/_homepage_form.html.erb
<%= display_errors(@collection) %>

<%= f.input :short_intro, input_html: { class: 'honeycomb_redactor'  } %>

<%= HoneypotThumbnail.display(f.object.honeypot_image) %>
<%= f.input :uploaded_image, as: :file %>

<%= f.input :show_page_title, as: :boolean, label: false, hint: "Select this box if your homepage image has your site title already embedded in it" do %>
  <label><%= f.check_box :hide_title_on_home_page %> Do not overlay site title on homepage image.</label>
<% end %>

app/views/collections/_list.html.erb
<table class="table table-striped item-list">
  <thead>
    <tr>
      <th><%= t('.title') %></th>
      <th></th>
      <th></th>
      <th><%= t('.status') %></th>
      <th><%= t('.updated_at') %></th>
    </tr>
  </thead>
  <tbody>
    <% collections.each do |collection| %>
      <tr>
        <td class="image">
          <%= CollectionImage.new(collection).display %>
        <td>
          <h4 class="media-heading"><%= h link_to collection.name_line_1, collection_path(collection) %></h4>
          <div><%= strip_tags collection.short_intro if collection.short_intro.present? %></div>
        </td>
        <td><span class="badge"><%= t('.items_badge', number: collection.items.size) %></span></td>
        <td>
          <%= PublishedText.display(collection) %>
        </td>
        <td>
           <%= ListTime.display(collection.updated_at) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/collections/_metadata_settings_form.html.erb
<%= react_component("MetaDataConfigurationForm", baseUpdateUrl: v1_collection_configurations_metadata_fields_path(@collection.unique_id)) %>

app/views/collections/_search_and_browse_form.html.erb
<%= f.input :enable_search, as: :boolean, label: false, hint: "Select this box to enable search for this collection" do %>
<label><%= f.check_box :enable_search %> Enable Site Search</label>
<% end %>
<%= f.input :enable_browse, as: :boolean, label: false, hint: "This will enable a browse page with all items listed." do %>
  <label><%= f.check_box :enable_browse %> Enable Item Browse</label>
<% end %>

app/views/collections/_settings_side_nav.html.erb
<h4>Settings</h4>
<ul class="nav nav-pills nav-stacked">
  <li class="<%= "active" if form.nil? || form == "general" %>"><%= link_to("General", settings_form_collection_path(collection, form: "general")) %></li>
  <li class="<%= "active" if form == "metadata" %>"><%= link_to("Metadata", settings_form_collection_path(collection, form: "metadata")) %></li>
</ul>

app/views/collections/_side_nav.html.erb
<% side_nav = CollectionsSideNav.new(collection: collection, form: form) %>
<h4>Site Content</h4>
<ul class="nav nav-pills nav-stacked">
  <li class="<%= side_nav.active_tab_class(tab: "homepage") %>"><%= side_nav.homepage_link %></li>
  <li class="<%= side_nav.active_tab_class(tab: "collection_introduction") %>"><%= side_nav.collection_introduction_link %></li>
  <li class="<%= side_nav.active_tab_class(tab: "about_text") %>"><%= side_nav.about_text_link %></li>
  <li class="<%= side_nav.active_tab_class(tab: "site_path") %>"><%= side_nav.site_path_link %></li>
</ul>

app/views/collections/index.html.erb
<% page_title(t('.page_title')) %>

<div class="jumbotron">
    <h1><%= t('.title') %></h1>
    <p><%= t('.description') %></p>
    <p>
      <% admin_or_admin_masquerading_only do %>
        <%= link_to raw("<i class=\"glyphicon glyphicon-plus\"></i> #{t('.new-button')}"),
          new_collection_path,
          :class => 'btn btn-primary btn-large' %>
      <% end %>
      <%= learn_more_button(help_path) %>
    </p>
</div>

<%= render partial: 'list', locals: { collections: @collections } %>

app/views/collections/settings.html.erb
<%= page_title(t('.title')) %>
<%= collection_nav(@collection, :settings) %>

<div class="row">
  <div class="col-md-10">
    <%= simple_form_for @collection, method: :put, :url => settings_update_form_collection_path(@collection, form: (params[:form] ? "#{params[:form]}" : 'general')) do |f| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Settings</h3>
        </div>
        <div class="panel-body">
          <%= render partial: (params[:form] ? "#{params[:form]}_settings_form" : 'general_settings_form'), locals: { f: f } %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-2">
    <%= render "settings_side_nav", collection: @collection, form: params[:form] %>
  </div>
</div>