config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { cas_sessions: "simple_cas" }
  root to: "collections#index"

  get "help", to: "help#help"

  get "404", to: "errors#catch_404"
  get "500", to: "errors#catch_500"

  resource :masquerades, only: [:new, :create] do
    get :cancel
  end

  resources :errors

  resources :collections,
            only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :import_google_sheet_callback, controller: "import"
      get :export_google_sheet_callback, controller: "export"
    end

    member do
      site_setup_constraints = { form: /homepage|collection_introduction|about_text|copyright_text|site_path/ }
      get :site_setup
      get "site_setup/:form", to: "collections#site_setup", as: :site_setup_form, constraints: site_setup_constraints
      put "site_setup/:form", to: "collections#site_setup_update", as: :site_setup_update_form, constraints: site_setup_constraints
      settings_constraints = { form: /general|metadata/ }
      get :settings
      get "settings/:form", to: "collections#settings", as: :settings_form, constraints: settings_constraints
      put "settings/:form", to: "collections#settings_update", as: :settings_update_form, constraints: settings_constraints
      put :publish
      put :unpublish
      post :get_google_import_authorization_uri, controller: "import"
      post :get_google_export_authorization_uri, controller: "export"
    end

    resources :items, only: [:index, :new, :create]
    resources :showcases, only: [:index, :new, :create]
    resources :pages, only: [:index, :new, :create]

    resources :editors, only: [:index, :create, :destroy] do
      collection do
        get :user_search
      end
    end
  end

  resources :items, only: [:edit, :update, :destroy] do
    member do
      put :publish
      put :unpublish
    end
    resources :children, controller: "item_children", only: [:new, :create]
  end

  resources :showcases, only: [:show, :edit, :update, :destroy] do
    member do
      get :title
      put :publish
      put :unpublish
    end
    resources :sections, only: [:index, :new, :create]
  end

  resources :pages, only: [:edit, :update, :destroy]

  resources :sections, only: [:edit, :update, :destroy]

  namespace :v1 do
    resources :collections,
              only: [:show, :index],
              defaults: { format: :json } do
      put :publish, defaults: { format: :json }
      put :unpublish, defaults: { format: :json }
      put :preview_mode, defaults: { format: :json }
      get :metadata_configuration, defaults: { format: :json }
      get :site_path, defaults: { format: :json }
      put :site_path, to: "collections#site_path_update", defaults: { format: :json }
      resources :search, only: [:index], defaults: { format: :json }
      resources :items, only: [:index, :create], defaults: { format: :json }
      resources :showcases, only: [:index], defaults: { format: :json }
      resources :pages, only: [:index], defaults: { format: :json }
      resource :configurations, defaults: { format: :json }, only: [:show] do
        resources :metadata_fields, only: [:create, :update, :destroy], defaults: { format: :json }
      end
    end
    resources :items,
              only: [:show, :update],
              defaults: { format: :json } do
      get :showcases, defaults: { format: :json }
    end
    resources :showcases, only: [:show], defaults: { format: :json }
    resources :pages, only: [:show], defaults: { format: :json }
    resources :sections, only: [:show], defaults: { format: :json }
  end

  namespace :api do
    resources :collections,
              only: [:index, :show],
              constraints: { format: /json/ } do
      resources :items, only: [:index, :show], constraints: { format: /json/ }
    end
  end

  namespace :admin do
    get "/", to: "administration#index"
    resources :external_collections
    resources :administrators, only: [:index, :create, :destroy] do
      collection do
        get :user_search
      end
    end
  end

  scope "/admin_old" do
    resources :users do
      put :set_admin
      put :revoke_admin
    end

    # NOTE About this route.
    # the "ids" that are searched on can have "." in the
    # and that throws off the rails routing. They need to
    # be passed in as query params and not as part of the
    # get string that is not /discovery_test_id/i,adf.adsfwe.adsfsdf
    # but as /discovery_test_id?id=i,adf.adsfwe.adsfsdf
    get "discovery_id_test", to: "discovery_id_test#show"
  end
end

app/models/shared/model_error_trapping.rb
module ModelErrorTrapping
  def self.included(base)
    base.extend(ClassMethods)
  end

  def raise_404
    fail ActionController::RoutingError.new("Not Found")
  end

  module ClassMethods
    def raise_404
      fail ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/shared/_back_action_bar.html.erb
<div class="menu-bar default">
  <div class="btn-group">
    <%= back_button(back_path) %>
  </div>
  <div class="pull-right">
    <div class="btn-group">
    <%= learn_more_button(learn_more_path) %>
  </div>
</div>

app/views/shared/_collection_left_nav.html.erb
<div class="nav-panel ">
  <ul class="well">
    <li class="<%= nav.active_section_css(:items) %>"><a href="<%= collection_items_path(nav.collection) %>"><i class="glyphicon glyphicon-picture"></i> <%= t('collection_left_nav.items') %></a></li>
    <li class="<%= nav.active_section_css(:showcases) %>"><a href="<%= collection_showcases_path(nav.collection) %>"><i class="glyphicon glyphicon-film"></i> <%= t('collection_left_nav.showcases') %></a></li>
    <li class="<%= nav.active_section_css(:pages) %>"><a href="<%= collection_pages_path(nav.collection) %>"><i class="glyphicon glyphicon-duplicate"></i> <%= t('collection_left_nav.pages') %></a></li>
    <li class="<%= nav.active_section_css(:website) %>"><a href="<%= site_setup_collection_path(nav.collection) %>"><i class="glyphicon mdi-av-web"></i> <%= t('collection_left_nav.website') %></a></li>
    <li role="presentation" class="divider"></li>
    <li class="<%= nav.active_section_css(:editors) %>"><a href="<%= collection_editors_path(nav.collection) %>"><i class="glyphicon glyphicon-user"></i> <%= t('collection_left_nav.editors') %></a></li>
    <li class="<%= nav.active_section_css(:settings) %>"><a href="<%= settings_collection_path(nav.collection) %>"><i class="glyphicon glyphicon-list-alt"></i> <%= t('collection_left_nav.settings') %></a></li>
    <li role="presentation" class="divider"></li>

    <li className="header" role="presentation">Publish Site</li>
    <li className="togglebutton">
      <%= react_component "CollectionPublishToggle", {
          publishPath: v1_collection_publish_url(nav.collection.unique_id),
          unpublishPath: v1_collection_unpublish_url(nav.collection.unique_id)
        }
      %>
    </li>

    <li className="header" role="presentation">Preview Site</li>
    <li className="togglebutton">
      <%= react_component "CollectionPreviewModeToggle", {
            previewModePath: v1_collection_preview_mode_url(nav.collection.unique_id)
          }
      %>
    </li>

    <%= react_component "CollectionPreviewPublishLink", {
          previewLinkURL: CreateBeehiveURL.call(nav.collection),
          previewLinkLabel: t('collection_left_nav.preview_site'),
          liveLinkLabel: t('collection_left_nav.live_site')
      }
    %>
  </ul>
  &nbsp;
  <a href="#" id="trig"><span id="switch" class="glyphicon glyphicon-chevron-left"></span></a>
</div>

app/views/shared/_collection_top_nav.html.erb
<ul class="nav navbar-nav">
  <li class="">
      <div class="btn-group collections"> <%= link_to(nav.collection.name_line_1, collection_path(nav.collection), class: "btn") %> <button data-toggle="dropdown" class="btn dropdown-toggle btn-primary" type="button"><span class="caret"></span></button>


    <ul class="dropdown-menu" role="menu">
      <li class="dropdown-header"><%= t('collection_top_nav.recent_collections') %></li>
      <% nav.recent_collections.each do | collection | %>
        <li><%= link_to(collection.name_line_1, collection_path(collection)) %></li>
      <% end %>
    </ul>
      </div>

  </li>
</ul>

<%= react_component "CollectionStoreInitializer", {
      collection: nav.collection
  }
%>

app/views/shared/_delete_panel.html.erb
<%
if can_delete
  message = "message"
  button_class = "btn btn-small btn-default btn-danger"
else
  message = "cannot_delete_message"
  button_class = "btn btn-small btn-default btn-danger disabled"
end
%>

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t('.title', default: 'Proceed with caution') %></h3>
  </div>
  <div class="panel-body">
    <h4 class=""><%= t("#{i18n_key_base}.heading", default: "Delete this #{default_name}") %></h4>
    <p class=""><%= t("#{i18n_key_base}.#{message}", default: "Proceed with caution. This will remove the #{default_name} and all associated data. ") %></p>
    <%= link_to content_tag('span', t("#{i18n_key_base}.heading", default: "Delete this #{default_name}") , class: ''),
                path,
                class: button_class,
                method: :delete,
                data: { confirm: "#{t("#{i18n_key_base}.message",
                        default: "Proceed with caution. This will remove the #{default_name} and all associated data. ")} Are you sure you wish to continue?" }
    %>
  </div>
</div>

app/views/shared/_display_flash_message.html.erb
<div class="<%= css_class %>">
  <%= content %>
</div>

app/views/shared/_error_messages.html.erb
<div class="alert alert-danger" role="alert">
  <strong>Opps!!</strong> <%= pluralize(obj.errors.count, "error") %> prohibited this form being saved.
</div>

app/views/shared/_no_back_action_bar.html.erb
<div class="menu-bar default">
  <div class="pull-right">
    <div class="btn-group">
    <%= learn_more_button(learn_more_path) %>
  </div>
</div>

app/views/shared/_page_title.html.erb
<div class="page-header">
  <div class="top-menu pull-right">
    <%= settings_link %>
  </div>
  <h1><%= title %> <small><%= small_title %></small></h1>
</div>

app/views/shared/_top_nav.html.erb
<div class="title-bar <%= nav.bar_size_class %>">
  <div class="container-fluid">
    <div class="row">
      <div class="navbar-header">
         <a class="navbar-brand" href="<%= root_path %>"><i class="glyphicon glyphicon-home"></i> honeycomb</a>
      </div>
      <div class="navbar-collapse collapse">

        <%= yield :collection_top_nav %>

        <ul class="nav navbar-nav navbar-right">
          <!--<li>
            <%= link_to "#" do %>
              <i class="glyphicon glyphicon-user"></i>
              <%= nav.current_user_display_name %>
            <% end %>
          </li>-->
          <% admin_only do %>
            <li>
              <%= link_to admin_path, title: "Administration"  do %>
                <i class="glyphicon glyphicon-cog"></i>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, title: "Log out" do %>
              <i class="glyphicon glyphicon-log-out"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>